### ISSUE TITLE
Control interface

### ISSUE THREAD

**Issue by teobiton** [teobiton/cryptopen#25]
Our register interface handles well the block to be hashed, as several tests for different parameters have shown.

What lacks so far is the communication with the core of the algorithm.
It's something to be defined as generic as possible for all components but I will focus on **Secure Hash Algorithms** for this issue.
I propose to add the following 32-bit  registers to handle communication with the core of the algorithm:

- Round counter: at any given cycles, holds the round counter value. For sha1 for example this value would be between 0 and 79. This is a Read Only register.
- Hash cycle: at any given cycle, holds the number of time the hash algorithm was performed. This could be compared with the specified message length value hold in the 64 LSBs of the block, so that users know the algorithm situation. Also Read Only.
- Control register: The control register could hold three bits as a starting point. One could be something like `enable` (R/W) and could be a way to start the computation. An other bit could be used to `hold` the calculation, this is intended for longer messages so that next value to be computed can be written to the registers. One `reset` bit to stop and reset calculation can be thought of. Finally, one could be `initial_state` (RO) to inform the user that the algorithm is at its initial point: it could be designed with a FSM in the core of the algorithm. 

@FromagePatin if you have time to check this out

**Comment by FromagePatin** [comment]
I agree with the following 32-bit registers you described.

Please find above my comments :

- Hash cycle : what do you mean by hash cycle ? According to the Secure Hash Standard specification (FIPS PUB 180-4), there are N messages blocks M and each message block M has a round counter value (80 for sha1 and 64 for sha256). Do you consider a message block M as a hash cycle ?

**Comment by teobiton** [comment]
Yes a message that requires say N blocks has N hash cycles. So a message that is single block will have 1 hash cycle.

**Comment by teobiton** [comment]
To continue on this, I think we should just support a memory mapped digest, it'll make things much easier.

Proposed description of registers (addresses are not shown since it's all generic):

| Register Name          | Description                                                | Width| Access Rights  |
| ----------------------------- | ------------------------------------------------------- | ------- | --------------------- |
|  **Block Register** | |||
| Data           | Input data block for SHA core computation | Configurable  | Read/Write      |
|  **Control and Status Register** | |||
| Enable Hash  | Enables or disables the hashing algorithm      | 1 bit  | Read/Write     |
| Reset Hash    | Resets the state of the hashing algorithm       | 1 bit  | Read/Write     |
| Hold State     | Indicates if the SHA core is in the hold state    | 1 bit  | Read Only       |
| Idle State       | Indicates if the SHA core is in the idle state     | 1 bit  | Read Only       |
| Digest Valid   | Hash output valid                                                  | 1 bit  | Read Only       |
|  **Hash digest** | |||
| Digest           | Digest output | Configurable  | Read Only      |

Most of this is already supported, the digest valid bit and digest registers must be added.
